docs_dir: docs/book
site_dir: docs/html
nav:
    - index.md
    - Introduction: intro.md
site_name: Mezzio Authorization middleware
site_description: 'Authorization middleware for Mezzio and PSR-7 applications'
repo_url: 'https://github.com/mezzio/mezzio-authorization'
