docs_dir: docs/book
site_dir: docs/html
pages:
    - Home: index.md
    - Introduction: v1/intro.md
    - Reference:
        - 'Authorization adapters': v1/auth-adapter.md
site_name: zend-expressive-authorization
site_description: 'Authorization middleware for Expressive and PSR-7 applications'
repo_url: 'https://github.com/zendframework/zend-expressive-authorization'
